name: main-build-test-release

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 21.0.5

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java }}
          cache: maven

      - shell: bash
        run: |
          ./gradlew clean check
